site_name: Cuckoo 3 docs
site_url: https://cuckoo-hatch.cert.ee/static/docs/
theme:
  name: readthedocs
  hljs_style: gml

extra_css:
  - style.css

markdown_extensions:
- admonition
- attr_list

plugins:
- include-markdown
- search:
    min_search_length: 2
    indexing: 'full'

docs_dir: src

nav:
- About:
  - Cuckoo3: about/cuckoo.md
  - Sandboxing: about/sandboxing.md
  - Terminology: about/terminology.md

- Installing:
  - Overview: installation/overview.md
  - System dependencies: installation/dependencies.md
  - Quickstart: installation/quickstart.md
  - VMCloak: installation/vmcloak.md
  - Cuckoo3: installation/cuckoo.md

- Configuring:
  - System system dependencies: configuration/system.md
  - VMCloak: configuration/vmcloak.md
  - Cuckoo3:
    - Cuckoo.yaml (needs work): configuration/cuckooconfs/cuckooyaml.md
    - Distributed.yaml (needs work): configuration/cuckooconfs/distributedyaml.md
    - Web configuration (needs work):
      - Web.yaml: configuration/cuckooconfs/webconfs/webyaml.md
    - Node configuration (needs work):
      - Routing.yaml (needs work): configuration/cuckooconfs/nodeconfs/routingyaml.md
  - Machinery modules (needs work): configuration/machineries.md
  - Network routing (needs work): configuration/routing.md

- Creating virtual machines:
  - VM creation: vms/vmcreation.md

- Using the web frontend:
  - WebUI (needs  work): web/ui.md

- Usage (needs work):
  - Submission: usage/submission/index.md
  - Web API:
    - Setup: usage/webapi/setup.md
    - Endpoints: usage/webapi/endpoints.md
  - Web UI: usage/webui/setup.md
  - Commands: usage/commands.md

- Developing your own(needs work):
  - Creating new machinery modules: development/creating_machinery.md

- Troubleshooting:
  - Common errors: errors/common.md
